language: android
jdk: oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support

    script:
            - ./gradlew wrapper --gradle-version 4.6
            - ./gradlew build
    before_install:
            - chmod +x gradlew